"""
Configuration defaults for JAE.
"""

# Default hyperparameters (from paper)
DEFAULT_LATENT_DIM = 6
DEFAULT_DROPOUT_P = 0.05
DEFAULT_LEARNING_RATE = 0.001
DEFAULT_WEIGHT_DECAY = 1e-5
DEFAULT_EPOCHS = 100
DEFAULT_BATCH_SIZE = 32
